### PR TITLE
Revert 5222067

### PR DESCRIPTION
**Pull request by emilio**
And apply the really worthy changes.

r? @SimonSapin

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-selectors/65)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good.

@bors-servo r+

**Comment by SimonSapin** [comment]
Published v0.4.0 on crates.io

**Comment by Ms2ger** [comment]
Curious about motivation here.

**Comment by SimonSapin** [comment]
@ecoal95 said parameterizing `SelectorMap` on `Element` was a pain when porting Servo.

**Comment by emilio** [comment]
@Ms2ger Basically made us parameterize all style, since the concrete `Element` types are only in the script side. 

Also not totally sure if it would work fine (since servo uses multiple `Element` types, but just one Stylist type for all of them if I'm not wrong).

BTW @SimonSapin the release seems to be broken (see the servo pull), have you previously seen something like that?

**Comment by SimonSapin** [comment]
That's likely https://github.com/rust-lang/cargo/issues/2326

**Pull request merged**
