### PR TITLE
Refactor attribute handling to remove the requirement to get attributes as strings

### PR DESCRIPTION
**Pull request by bholley**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-selectors/91)

### CODE REVIEW

**Comment by bholley** [comment]
This will be helpful for stylo, since marshaling non-atomized gecko strings into servo requires utf16->utf8 conversion.

**Comment by SimonSapin** [comment]
r=me with a method renamed.

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/parser.rs, line 26 [r5]](https://reviewable.io:443/reviews/servo/rust-selectors/91#-KLs1SgqWD92A3I-m7QO:-KLs1SgqWD92A3I-m7QP:1483192293) ([raw file](https://github.com/servo/rust-selectors/blob/9030fcaf4b18ffc28414e3786205e07019b75ea7/src/parser.rs#L26)):_

> ``` Rust
> pub trait MaybeAtom: Clone + Debug + HeapSizeOf + PartialEq {
>     fn equals_atom(&self, other: &Atom) -> bool;
>     fn from_cow_str<'a>(cow: Cow<'a, str>) -> Self;
> ```

Nit: this lifetime parameter (and others) can be elided.

---

_[src/tree.rs, line 21 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/91#-KLs-X_Jz4PwNQOeXc0Z:-KLs-X_Jz4PwNQOeXc0_:792915223) ([raw file](https://github.com/servo/rust-selectors/blob/8618f205d030cd05d17a53d489a739b3fa0a7b91/src/tree.rs#L21)):_

> ``` Rust
>     fn match_attr_has(&self, attr: &AttrSelector) -> bool;
>     fn match_attr_equals(&self, attr: &AttrSelector, value: &str) -> bool;
>     fn match_attr_equals_ignore_case(&self, attr: &AttrSelector, value: &str) -> bool;
> ```

Please rename to `match_attr_equals_ignore_ascii_case`. It’s annoyingly long, but it helps stop someone who might be tempted to use some Unicode caseless matching algorithm.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-selectors/91#-:-KLs2IOl2Iv2xnunIUDd:1333056902)_

**Pull request merged**
