### PR TITLE
Simplify some APIs

### PR DESCRIPTION
**Pull request by SimonSapin**
@Ms2ger r?

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-selectors/37)

### CODE REVIEW

**Comment by SimonSapin** [comment]
This is mostly cosmetic, we might wanna try it in Servo before landing to see if the impls look better.

**Comment by Ms2ger** [comment]
I think there's some behaviour changes here; will look later.

**Comment by SimonSapin** [comment]
Are you thinking of the `element.parent_element().is_some()` checks in `:first-child` and friends? The Selectors Level 4 spec disagrees with Level 3 on this point, but I think is preserved the previous behavior of the code (which align(ed|s) with Level 3.)

**Comment by SimonSapin** [comment]
What this looks like in an impl: https://github.com/SimonSapin/kuchiki/compare/selectors_pr37

**Comment by Ms2ger** [comment]
Yeah, it changes the behaviour of `:first-child` and friends, and `:root`, when the parent node is a `DocumentFragment`. Selectors 4 doesn't seem to change `:root`, so we'll need to keep the current behaviour there. Have you checked if these changes make any wpt tests fail? If not, we should add tests.

**Comment by SimonSapin** [comment]
What should these pseudo-classes do when the parent is a `DocumentFragment`? It’s not clear to me from reading the spec.

**Comment by SimonSapin** [comment]
Added two commits to align the behavior with Selectors Level 4.

**Pull request merged**
