### PR TITLE
Implement :empty pseudo selector

### PR DESCRIPTION
**Pull request by frewsxcv**
http://dev.w3.org/csswg/selectors-3/#empty-pseudo

### CODE REVIEW

**Comment by frewsxcv** [comment]
Not sure why Travis isn't picking this up...

**Comment by SimonSapin** [comment]
I think this incorrectly doesn’t match `<p><!-- only a comment --></p>` for example. The `Node` trait probably needs a new method like `fn is_element_or_non_empty_text(&self) -> bool;`. (CDATA nodes and entity reference nodes don’t exist anymore, parsers emit text nodes instead.)

> Not sure why Travis isn't picking this up...

https://travis-ci.org/servo/rust-selectors/requests says "branch not included or excluded". @metajack, do you know if acc832346bf6aa5fd09a98c42f8b439ffc6324b8 would exclude PRs?

**Comment by frewsxcv** [comment]
> I think this incorrectly doesn’t match `<p><!-- only a comment --></p>` for example

Ah, you're right. I forgot that comments are `Object`s and are considered `Node`s. I'll add in that trait method

**Comment by frewsxcv** [comment]
Let me know how that latest push looks

**Comment by frewsxcv** [comment]
Let me know how that latest push looks

**Pull request merged**
