### PR TITLE
matching: Make ElementFlags work as intended.

### PR DESCRIPTION
**Pull request by emilio**
…StyleRelations.

r? @SimonSapin 

cc @bholley

---

This change is [Reviewable](https://reviewable.io/reviews/servo/rust-selectors/98)

### CODE REVIEW

**Comment by SimonSapin** [comment]
r+ with a breaking version number bump

**Comment by emilio** [comment]
@bors-servo: r-
- Need to double-check something.

**Comment by emilio** [comment]
Heh, the following test case fails on Servo:

``` html
<!doctype html>
<style>
  .container div {
    width: 50px;
    height: 50px;
    background: blue;
  }
  .container div:nth-child(2) {
    background: red;
  }
</style>
<div class="container">
  <div></div>
</div>
<script>
  let container = document.querySelector('.container');
  window.onload = function() {
    container.insertBefore(document.createElement('div'), container.firstChild)
  }
</script>
```

It not only fails with these changes, but also without them. Nontheless knowing this flaw these changes don't make that much sense, I guess, sigh.

**Comment by SimonSapin** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/matching.rs, line 13 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/98#-KQXZ72lTqPX1BiuinP5:-KQXZ72lTqPX1BiuinP6:b-qzc36a) ([raw file](https://github.com/servo/rust-selectors/blob/ddbb362d646b78eb89b75b7de00b6f9e8782b12a/src/matching.rs#L13)):_

> ``` Rust
> 
> #[derive(Copy, Clone, Debug, PartialEq, Eq)]
> pub enum MatchingReason {
> ```

Please document what this is for and what each value means.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-selectors/98)_

**Comment by emilio** [comment]
I was suspicious about the correctness of `is_rightmost_selector`, so I dropped that.

@bors-servo: r=SimonSapin

**Pull request merged**
