### PR TITLE
Make TNode::as_element() return an Option

### LINKED ISSUE #22: Make TNode::as_element() return an Option
Why panic and have is_element() when you can return an Option?

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes #22

---

No one was making progress on this, so I decided to do it

### CODE REVIEW

**Comment by frewsxcv** [comment]
I'll eventually make the changes into servo in the next day or so

**Comment by Ms2ger** [comment]
I'm not sure if this is the right approach. Right now, all these callers panic if they find a non-Element, and now they'll silently do... something. I think a better first step would be to replace all `as_element()` calls by `as_element().unwrap()`, and as a second step, see if there's any code of the form

``` rust
if n.is_element() {
    let e = n.as_element().unwrap();
    ...
}
```

and translate it to

``` rust
if let Some(e) = n.as_element() {
    ...
}
```

**Comment by SimonSapin** [comment]
I agree with Ms2ger. But few of the `as_element` calls are in that form. I take this as a sign that most of this code should work with elements rather than nodes to begin with. I’ll change the signatures.

**Comment by SimonSapin** [comment]
Thanks for the patch anyway!

**Comment by frewsxcv** [comment]
:+1: 

After I opened the pull request yesterday, I had the same concerns, so I'm glad to hear my beliefs were confirmed.

**Pull request closed without merging**
