### PR TITLE
Use bitflags 0.5

### PR DESCRIPTION
**Pull request by saurvs**
Part of https://github.com/servo/servo/issues/10077

---

This change is [Reviewable](https://reviewable.io/reviews/servo/rust-selectors/77)

### CODE REVIEW

**Comment by KiChjang** [comment]
Not sure if the lockfiles need to be updated as well, otherwise r=me.

**Comment by Ms2ger** [comment]
Note that all bitflags are private by default in 0.5.

**Comment by SimonSapin** [comment]
@KiChjang `Cargo.lock` is in `.gitignore` for this repository.

@saurvs this change as-is will likely break Servo, per what @Ms2ger says. Please use http://doc.crates.io/guide.html#overriding-dependencies to build it against your branch of rust-selectors. You should see a build error about `ElementFlags` being private, and you’ll be able to test a fix and update this PR.

I keep in my `.cargo/config` file a bunch of path overrides commented-out, one per line, so I can uncomment them as needed.

**Comment by saurvs** [comment]
@KiChjang The crate builds now.

**Pull request merged**
