### PR TITLE
Use string-cache from crates.io

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
@metajack Please add homu support here. Thanks!

**Comment by SimonSapin** [comment]
@metajack https://travis-ci.org/servo/rust-selectors/builds/66945743 succeeded but this PR was not merged. Is some configuration missing?

I’m merging this manually since dependents (Kuchiki) are broken without it at the moment.

**Comment by metajack** [comment]
I think I hadn't redeployed salt. It should be working now.

**Pull request merged**
