### PR TITLE
Use associated types for TNode.

### LINKED ISSUE #9: Use associated types in tree.rs
`TNode` should have an `Element` associated type bound to `TElement` instead of the `E` type parameter. Servo will then need to be updated accordingly.

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
Fix #9

### CODE REVIEW

**Comment by SimonSapin** [comment]
Thanks! A couple notes, though:

Is it possible to remove `<Element = TElement<'a>>` in all `matching.rs` signatures if the bound is specified in the trait declaration? I.e. `type Element: TElement<'a>` in `tree.rs`

I’m not sure about changing all the `TElement` methods from taking `self` by value to taking `&self` by reference. I think there was a reason for having it by value, though I’m not sure what it was. I think the types implementing `TElement` and `TNode` in Servo are smart-pointer references that are cheap to copy, not the element or node themselves. @jdm or @Ms2ger, can you comment?

**Comment by jdm** [comment]
Yes, `TNode` at least is implemented by `JSRef<Node>` so &self is just another level of pointer indirection.

**Comment by tetsuharuohzeki** [comment]
updated :)

**Comment by SimonSapin** [comment]
Looks good, thanks! Are you interested in porting Servo for this change as well?

**Comment by tetsuharuohzeki** [comment]
@SimonSapin ok. I start to work update the servo's dependency for this.

But the current revision of this include [this](https://github.com/servo/string-cache/pull/65), the porting this change will need to upgrade html5ever.

**Pull request merged**
