### PR TITLE
Redesign the style sharing API.

### PR DESCRIPTION
**Pull request by emilio**
See https://github.com/servo/servo/pull/12668 for context.

r? @SimonSapin

---

This change is [Reviewable](https://reviewable.io/reviews/servo/rust-selectors/93)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I like it! Just some details…

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[src/matching.rs, line 314 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOo_YPE2RPUuVrQvsme:-KOo_YPE2RPUuVrQvsmf:b-4oiimi) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L314)):_

> ``` Rust
>     ///
>     /// This is used to implement efficient sharing.
>     pub flags StyleRelations: u16 {
> ```

What’s the difference between `StyleRelations` and `ElementFlags`? Why shouldn’t they be merged?

---

_[src/matching.rs, line 316 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoYv_HiAsvUiWjb_bw:-KOoYv_IT_mOYu8wrFVP:b-m0bgv6) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L316)):_

> ``` Rust
>     pub flags StyleRelations: u16 {
>         /// Whether this element has matched any rule that is determined by a
>         /// sibling (i.e., when using the `+` combinator).
> ```

Nit: make this comment exhaustive: s/i.e., when using the `+` combinator/when using a `+` or `~` combinator/.

---

_[src/matching.rs, line 323 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoZJdbfdc-8flqcv5r:-KOoZJdbfdc-8flqcv5s:b-5y3dyx) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L323)):_

> ``` Rust
>         /// nth-child, etc.).
>         ///
>         /// XXX improve this description and name, "position" is too generic.
> ```

Is that what the spec calls "tree-structural pseudo-classes"? https://drafts.csswg.org/selectors/#structural-pseudos Or just the child-indexed and typed child-indexed?

---

_[src/matching.rs, line 331 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoZnLZNBJX09I4bS1T:-KOoZnL_RYkolu32S4_S:b3xmibi) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L331)):_

> ``` Rust
> 
>         /// Whether this element is affected by a (probably) unique selector,
>         /// like an ID selector.
> ```

This is only used used for ID selectors, so maybe call it that?

---

_[src/matching.rs, line 406 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoa1zlgvZfjMKrRXzz:-KOoa1zlgvZfjMKrRY--:b-erv4d9) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L406)):_

> ``` Rust
>             match selector.next {
>                 Some((_, Combinator::NextSibling)) |
>                 Some((_, Combinator::LaterSibling)) => *relations |= AFFECTED_BY_SIBLINGS,
> ```

Is this really only the case when the selector matches? In https://github.com/servo/rust-selectors/pull/94 I’ve done it in `matches_compound_selector_internal` regardless of match result, but I don’t know if that’s necessary for correctness or overly conservative.

Specifically, the test failure I was hitting has a `div + div` selector and to consecutive `<div>` elements. The first element did not match that selector, but the second would and therefore needs to not share style with the first.

Try `./mach test-css /css21_dev/html4/absolute-replaced-height-017.htm` in Servo for that one case.

---

_[src/matching.rs, line 633 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoblyvZ_434KyawsZw:-KOoblywhXJNZqH9Wfrq:b-qbv5li) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L633)):_

> ``` Rust
>         // TODO: case-sensitivity depends on the document type and quirks mode
>         SimpleSelector::ID(ref id) => {
>             relation_if!(element.get_id().map_or(false, |attr| attr == *id), AFFECTED_BY_UNIQUE_SELECTOR)
> ```

Same comment (here and and many times in this function) as above for sibling combinators: should a negative result not also disable style sharing?

---

_[src/matching.rs, line 376 [r3]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOod0udKbcuIMVWvBx0:-KOod0udKbcuIMVWvBx1:b-9gesuy) ([raw file](https://github.com/servo/rust-selectors/blob/fac4c060337de386bb5173457929b853e96d7a2a/src/matching.rs#L376)):_

> ``` Rust
>         ///
>         /// XXX This value is bogus, but there's a servo bug on its handling.
>         /// Will fix after the style cache thing lands.
> ```

Don’t you need to update Servo anyway to use a Selectors version with this PR?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-selectors/93#-:-KOodV42Sfa3M1qNzZjA:bs6f777)_

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[src/matching.rs, line 314 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOo_YPE2RPUuVrQvsme:-KOpO98sXyzY2cy4wQz_:befu331) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L314)):_
<details><summary>

<i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>



> What’s the difference between `StyleRelations` and `ElementFlags`? Why shouldn’t they be merged?
> </details>
> `StyleRelations` aren't persisted anywhere, while `ElementFlags` are hints to the parent element to know when a child should be restyled.

`StyleRelations` is a cheap way of knowing what kind of rules applied to a element, but do not need to be stored anywhere after selector matching, while `ElementFlags` are a way of telling a parent what kind of rules applied to its direct children.

---

_[src/matching.rs, line 316 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoYv_HiAsvUiWjb_bw:-KOpQFy3X07v1PtOcCR2:b-896fix) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L316)):_
<details><summary>

<i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>



> Nit: make this comment exhaustive: s/i.e., when using the `+` combinator/when using a `+` or `~` combinator/.
> </details>
> Done.

---

_[src/matching.rs, line 323 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoZJdbfdc-8flqcv5r:-KOpQfB4zY5IA73-DHFM:b2q8x1o) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L323)):_
<details><summary>

<i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>



> Is that what the spec calls "tree-structural pseudo-classes"? https://drafts.csswg.org/selectors/#structural-pseudos Or just the child-indexed and typed child-indexed?
> </details>
> This is used only by child-indexed and type child-indexed.

---

_[src/matching.rs, line 331 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoZnLZNBJX09I4bS1T:-KOpQelczby2Qc84N2_d:b-896fix) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L331)):_
<details><summary>

<i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>



> This is only used used for ID selectors, so maybe call it that?
> </details>
> Done.

---

_[src/matching.rs, line 406 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoa1zlgvZfjMKrRXzz:-KOpOfIFM8DkSioHu6UN:b-xd19gq) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L406)):_
<details><summary>

<i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>



> Is this really only the case when the selector matches? In https://github.com/servo/rust-selectors/pull/94 I’ve done it in `matches_compound_selector_internal` regardless of match result, but I don’t know if that’s necessary for correctness or overly conservative.
> 
> Specifically, the test failure I was hitting has a `div + div` selector and to consecutive `<div>` elements. The first element did not match that selector, but the second would and therefore needs to not share style with the first.
> 
> Try `./mach test-css /css21_dev/html4/absolute-replaced-height-017.htm` in Servo for that one case.
> </details>
> The idea is stop disabling selector sharing depending on what rules apply, and start doing it depending on what rules _match_, then rejecting it based on more specific rules. https://github.com/servo/servo/pull/12668 needs a rebase, but the over-all strategy still applies.

Also, note that that Servo PR passed all the tests :)

---

_[src/matching.rs, line 633 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoblyvZ_434KyawsZw:-KOpPSGzFQoJ7nJH33HW:bc0yfs5) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L633)):_
<details><summary>

<i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>



> Same comment (here and and many times in this function) as above for sibling combinators: should a negative result not also disable style sharing?
> </details>
> Same reply as above, we don't want an ID selector that could potentially apply to disable style sharing completely :)

---

_[src/matching.rs, line 376 [r3]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOod0udKbcuIMVWvBx0:-KOpOVaRA6QyIaRsuD3A:bsunkxn) ([raw file](https://github.com/servo/rust-selectors/blob/fac4c060337de386bb5173457929b853e96d7a2a/src/matching.rs#L376)):_
<details><summary>

<i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>



> Don’t you need to update Servo anyway to use a Selectors version with this PR?
> </details>
> Yes, but it's a fairly large change, so I'd prefer to keep the things separated: https://github.com/servo/servo/pull/12668

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-selectors/93)_

**Comment by SimonSapin** [comment]
Reviewed 1 of 2 files at r6, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/matching.rs, line 323 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoZJdbfdc-8flqcv5r:-KOpSSRRKIi-wLixv4Qw:btads7t) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L323)):_
<details><summary>

<i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>



> This is used only by child-indexed and type child-indexed.
> </details>
> Maybe rename "position" to "child index", then?

---

_[src/matching.rs, line 376 [r3]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOod0udKbcuIMVWvBx0:-KOpSYUtUj4GwYJ9Cmss:b-9955jd) ([raw file](https://github.com/servo/rust-selectors/blob/fac4c060337de386bb5173457929b853e96d7a2a/src/matching.rs#L376)):_
<details><summary>

<i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>



> Yes, but it's a fairly large change, so I'd prefer to keep the things separated: https://github.com/servo/servo/pull/12668
> </details>
> I have some reluctance to shipping a known bug in a public API, but I’ll leave it to your judgment.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-selectors/93)_

**Comment by emilio** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/matching.rs, line 323 [r2]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOoZJdbfdc-8flqcv5r:-KOpTAxHohY2mz2EMrUZ:b-896fix) ([raw file](https://github.com/servo/rust-selectors/blob/31aa35387fd4b8df8c3e80248a7e28d4d0dd3023/src/matching.rs#L323)):_
<details><summary>

<i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>



> Maybe rename "position" to "child index", then?
> </details>
> Done.

---

_[src/matching.rs, line 376 [r3]](https://reviewable.io:443/reviews/servo/rust-selectors/93#-KOod0udKbcuIMVWvBx0:-KOpTLfuBGDGfgcdwtxI:bgn36ak) ([raw file](https://github.com/servo/rust-selectors/blob/fac4c060337de386bb5173457929b853e96d7a2a/src/matching.rs#L376)):_
<details><summary>

<i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>



> I have some reluctance to shipping a known bug in a public API, but I’ll leave it to your judgment.
> </details>
> FWIW we're already shipping it, but... sounds ok, I'll fix the handling in servo, even if it's a temporary fix that just alias the flags. I've just dropped that commit.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-selectors/93)_

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-selectors/93#-:-KOpVCHtahpbrqTv6467:bkg9nno)_

**Comment by SimonSapin** [comment]
https://travis-ci.org/servo/rust-selectors/builds/151282934 is green.

**Pull request merged**
