### PR TITLE
Fix empty values and values with whitespace in attribute selectors

### PR DESCRIPTION
**Pull request by SimonSapin**
https://github.com/servo/servo/issues/15394

Also use `?` syntax. I recommend looking at the two commits separately.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-selectors/104)

### CODE REVIEW

**Review by emilio — APPROVED** [review]
r=me assuming you're landing this with tests in servo.

**Comment by emilio** [comment]
whoops, ok, was reviewing before the review request, happy to delegate the review to @mbrubeck  :)

**Comment by SimonSapin** [comment]
@emilio I requested review from Matt so that at least one person would look at it, but if you want to do it please do :)

**Comment by SimonSapin** [comment]
Oh you’ve even already approved it. Thanks!

@bors-servo r=emilio

**Pull request merged**
