### PR TITLE
Release version 0.5.1

### PR DESCRIPTION
**Pull request by mbrubeck**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-selectors/72)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Includes #71. Note: This is a minor release because the added `Element` method has a default implementation, so it is optional for implementors of the trait. r? @SimonSapin

**Comment by SimonSapin** [comment]
@bors-servo r+

For what it’s worth, I’m in favor of including version number changes in PRs that you’re gonna want published. No need to make it a separate PR IMO.

**Comment by mbrubeck** [comment]
Published

**Comment by KiChjang** [comment]
I favor same PR, different commits, if that's ok with you.

**Comment by SimonSapin** [comment]
@KiChjang yeah, that sounds fine. My point is how many synchronization points between people in different time zones we need.

**Pull request merged**
