### PR TITLE
Extract Selector matching code from Servo

### PR DESCRIPTION
**Pull request by SimonSapin**
I did not preserve the commit history of the relevant files. Look in the Servo repository from https://github.com/servo/servo/tree/d26345f868e4261760ce204bdc383941e8f14621 and back for that.

Imported files are:
- `components/style/selectors.rs` -> `src/parser.rs`
- `components/style/selector_matching.rs` -> `src/matching.rs`
- `components/style/node.rs` -> `src/tree.rs`
- `components/util/bloom.rs` -> `src/bloom.rs`
- `components/util/sort.rs` -> `src/quicksort.rs`
- `components/util/smallvec.rs` -> `src/smallvec.rs`

This library currently targets rustc 80627cd3c 2015-02-07, the version currently used by Servo, which is a few weeks behind Rust Nightly. Against convention for libraries, Cargo.lock is included in the repository since it was tricky to get right: many dependencies have been upgraded for further breaking changes in the language or standard library, so we need a version that is not the latest.

### CODE REVIEW

**Comment by larsbergstrom** [comment]
I think this looks fine to me - it's kinda hard to track 100% of the line movements between repos, though.

**Comment by SimonSapin** [comment]
FWIW, the first commit copies the files exactly as they were in https://github.com/servo/servo/commit/d26345f868e4261760ce204bdc383941e8f14621.

**Comment by SimonSapin** [comment]
@filsmick this is a thing now! The API still needs a lot of work, however.

**Comment by jdm** [comment]
@SimonSapin Were you intending to merge this before landing the Servo PR?

**Comment by SimonSapin** [comment]
These changes are already on master so that I didn’t have to add `branch = "..."` to Servo’s Cargo.toml files. (Cargo looks for a Cargo.toml for git dependencies even if they have a path override). This PR was only to help review.

**Comment by SimonSapin** [comment]
@filsmick See http://users.rust-lang.org/t/kuchiki-a-vaporware-html-xml-tree-manipulation-library/435

**Comment by yberreby** [comment]
@SimonSapin Thank you very much for remembering me! :)
If there's anything you think I can do to help, tell me!

Are there plans to add documentation?

**Comment by SimonSapin** [comment]
@filsmick Check out the users.rust-lang.org link above, discuss there if you want to say something, and maybe participate in making this thing happen ! I’m confident other people will be interested too.

**Pull request merged**
